package ru.pepsxx.spring.help.v000_pre_start.liquibase_util;

import liquibase.Liquibase;
import liquibase.database.jvm.JdbcConnection;
import liquibase.exception.LiquibaseException;
import liquibase.resource.ClassLoaderResourceAccessor;
import ru.pepsxx.spring.help.v000_pre_start.connect_util.ConnectUtil;

import java.sql.Connection;
import java.sql.SQLException;

public class LiquibaseUtil {
    private LiquibaseUtil() {
    }

    static public void start() throws LiquibaseException, SQLException {
        System.out.println("""
                ****************************************************************************************************
                liquibase
                Зависимости:
                1.  liquibase-core
                
                Настройки в resources/db/changelog:
                1.  db.changelog-master.yaml
                2.  db.changelog-1.0.sql
                3.  ...
                
                1:
                databaseChangeLog:
                    - include:
                        file: db/changelog/db.changelog-1.0.sql
                
                2:
                --liquibase formatted sql
                --changeset pep_sxx:1
                CREATE TABLE Person
                (
                    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR NOT NULL
                );
                ****************************************************************************************************""");
        try (Connection connection = ConnectUtil.getConnection()) {
            new Liquibase(
                    "db/changelog/db.changelog-master.yaml",
                    new ClassLoaderResourceAccessor(),
                    new JdbcConnection(connection)
            ).update("");
            System.out.println("Liquibase - Обновлен");
        }
    }
}
